name: Publish

on:
  push:
    branches:
      - master

# 参考一下这个: https://github.com/timeshiftsauce/CeruMusic/blob/main/.github/workflows/main.yml
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, 'release')

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always -mw
